CREATE TABLE CUSTOMER_TBL (CUSTID INT IDENTITY(1,1) NOT NULL, F_NAME VARCHAR(255) NOT NULL, L_NAME VARCHAR(255) NOT NULL, 

BILL_ADDRESS VARCHAR(255) NOT NULL, BILL_CITY VARCHAR(255) NOT NULL, BILL_STATE VARCHAR(255) NOT NULL, BILL_ZIP VARCHAR(7) NOT NULL, 

PHONE VARCHAR(15) NOT NULL, COMPANY VARCHAR(255)NULL, EXT INT NULL, 

CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTID)); 

  

CREATE TABLE PRODUCT(PRODUCTID INT IDENTITY(1,1) NOT NULL, PRODUCT_NAME VARCHAR(255) NOT NULL, PRODUCT_PRICE VARCHAR(255) NOT NULL, 

PRODUCT_AMT VARCHAR(255) NOT NULL, 

CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCTID)); 

  

CREATE TABLE ORDERS(ORDERID INT IDENTITY (1,1) NOT NULL, CUSTID INT NOT NULL,SHIP_ADDRESS VARCHAR(255) NOT NULL, SHIP_CITY VARCHAR(255) NOT NULL, 

SHIP_STATE VARCHAR(255) NOT NULL, SHIP_ZIP VARCHAR(7) NOT NULL, ORDERDATE DATETIME NULL,  

CONSTRAINT ORDER_PK PRIMARY KEY (ORDERID), 

CONSTRAINT CUST_FK FOREIGN KEY (CUSTID) REFERENCES CUSTOMER_TBL(CUSTID)); 

  

CREATE TABLE ORDER_DETAILS (ORDERID INT NOT NULL, PRODUCTID INT NOT NULL, QUANTITY INT NOT NULL, 

CONSTRAINT OD_PK PRIMARY KEY (ORDERID,PRODUCTID), 

CONSTRAINT ORDERID2_FK FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID), 

CONSTRAINT PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)); 
